# models.conf
# Format: model_name=model_path  (local path or HuggingFace model ID)
Mistral-Large-Instruct-2411=mistralai/Mistral-Large-Instruct-2411
Qwen2.5-72B-Instruct=Qwen/Qwen2.5-72B-Instruct
Gemma-3-27b-it=google/gemma-3-27b-it
Llama-4-Scout-17B-16E-Instruct=meta-llama/Llama-4-Scout-17B-16E-Instruct
Athene-V2-Chat=Nexusflow/Athene-V2-Chat
GLM-4-32B-0414=THUDM/GLM-4-32B-0414
Command-a=CohereForAI/c4ai-command-a-03-2025
Qwen3-235B=Qwen/Qwen3-235B-A22B-Instruct-2507