"""
    prompt with "seed" inside can find relevant example in seed_prompt.py
"""


JUDGE_QUERYER_TAG_DOCUMENT_CORRECT_PROMPT="""You are evaluating the answerability of a question generated by a large language model based on a given document. Please read the document and the question carefully. Then, rate the question based on the following criteria:

**Example Scenario:**

**Document:**
Singapore, officially the Republic of Singapore, is a sovereign island city-state in maritime Southeast Asia. It lies about one degree of latitude (137 kilometres or 85 miles) north of the equator, off the southern tip of the Malay Peninsula, bordering the Strait of Malacca to the west, the Singapore Strait to the south, the South China Sea to the east, and the Straits of Johor to the north. Singapore is one of the most densely populated countries in the world, with a multicultural population and strong international trade links. Its history dates back to the 13th century, but modern Singapore was founded in 1819 by Sir Stamford Raffles as a British trading post.

**Question:**
What year did Singapore gain independence?

**Answerability Rating Scale:**

5 - Fully Answerable:** The question can be clearly and completely answered using only the information present in the provided document. The answer is explicitly stated or can be directly inferred without external knowledge.
4 - Mostly Answerable:** The question can be answered using the information in the document, but some minor external knowledge or common sense might be helpful for a complete understanding.
3 - Partially Answerable:** The document provides some relevant information to the question, but it does not contain a complete answer. Additional information from outside the document is required.
2 - Minimally Answerable:** The document contains very little or indirect information related to the question, making it difficult to answer adequately.
1 - Not Answerable:** The question cannot be answered based on the information provided in the document. The document lacks relevant information, or the question is completely unrelated to the document.



**Justification:**
The document discusses the founding of modern Singapore in 1819 but does not mention when Singapore gained independence. Therefore, the question cannot be answered based on the provided text.

**Rating:** 1
---

**Now, it's your turn to evaluate a new question based on a new document using the same scale:**

**Document:**
{DOCUMENT}

**Question:**
{QUESTION}

"""


JUDGE_QUERY_RELATED_TO_CORRECT_DOCUMENT_PROMPT="""You are provided with several reference documents and a question. Each document begins with its unique identifier in the format [Document ID]. Your task is to determine which one document is the most probable source for the answer to the question. You must select only one document.

**Example Scenario:**

**Documents:**
[1] The Eiffel Tower, located in Paris, France, was completed in 1889 for the World's Fair. It is one of the most recognizable structures globally and stands 330 meters tall. Gustave Eiffel's company designed and built the tower.
---
[2] The Statue of Liberty, a gift from France to the United States, stands on Liberty Island in New York Harbor. It was dedicated on October 28, 1886. It represents Libertas, the Roman goddess of freedom.
---
[3] Big Ben is the nickname for the Great Bell of the striking clock at the north end of the Palace of Westminster in London, UK. The tower housing the clock is officially named the Elizabeth Tower. It was completed in 1859.

**Question:**
Who designed the Eiffel Tower?

**Justification:**
Document [1] is the only document that discusses the Eiffel Tower and explicitly mentions that "Gustave Eiffel's company designed and built the tower". Documents [2] and [3] describe the Statue of Liberty and Big Ben, respectively, and contain no information relevant to the designer of the Eiffel Tower.
**Document ID:**
[1]
---

**Now, it's your turn to determine which one document is the most probable source:**

**Documents:**
{DOCUMENTS}

**Question:**
{QUESTION}

"""



JUDGE_QUERY_ATOMICITY="""Your task is to determine if the question is **atomic** (asks for a single piece of information or addresses a single, indivisible topic) or **non-atomic (composite)** (combines multiple distinct sub-questions). Please read the question carefully. Then, rate the question based on the following criteria:


**Rating Scale:**
1 - The question is Atomic.
0 - The question is Non-atomic (Composite).


**Example Scenario:**

**Question:**
What is the boiling point of water at standard atmospheric pressure?

**Justification:**
This question asks for a single, specific piece of factual information. It cannot be broken down. Therefore, it is atomic.

**Rating:**
1
---

**Example Scenario:**

**Question:**
Who wrote "Hamlet" and in what year was it first performed?

**Justification:** 
This question combines two distinct sub-questions: 1) Who wrote "Hamlet"? and 2) When was it first performed? These are separate pieces of information. Therefore, it is non-atomic (composite).

**Rating:**
0
---

**Now, evaluate the following question and provide only the classification number (0 or 1):**

**Question:**
{QUESTION}

"""







JUDGE_QUERY_Explicit_Reference="""Your task is to determine if the question **explicitly mentions** relying on a specific document, context, text, or provided information to be answered. Look for phrases such as "based on the document", "according to the context", "in the provided text", "using the information below", "referring to the article", etc. Please read the question carefully. Then, rate the question based on the following criteria:

**Rating Scale:**
0 - If the question contains explicit wording indicating reliance on an external document or context.
1 - If the question does NOT contain such explicit wording. (The question might *implicitly* require external knowledge or context to be answered, but it doesn't *state* it).


**Example Scenario:**

**Question:**
Based on the provided article, what are the main risks discussed?

**Justification:**
The question explicitly uses the phrase "Based on the provided article", indicating reliance on an external document.

**Rating:**
0
---

**Example Scenario:**

**Question:**
What is the capital of Australia?

**Justification:**
The question asks for a general knowledge fact and does not contain any explicit phrase referring to a specific document or context provided.

**Rating:**
1
---

**Now, evaluate the following question based on these rules:**

**Question:**
{QUESTION}

"""



JUDGE_RESPONSE_FAITHFUL_PROMPT="""You are tasked with evaluating the faithfulness of a response generated by a large language model. Your goal is to determine how accurately the response reflects the information presented in the provided source document. Please read the document and the response carefully. Then, rate the response based on its faithfulness to the document using the following criteria:

**Faithfulness Rating Scale:**

5 - Fully Faithful:** The entire response is directly supported by the information present in the provided document. All claims made in the response can be clearly verified against the document. No information is introduced that is not found in the document.
4 - Mostly Faithful:** The core claims and the majority of the information in the response are supported by the document. It might contain minor details or phrasing not explicitly found in the document, but these additions do not contradict the source information and are reasonable inferences or rephrasing.
3 - Partially Faithful:** The response contains a mix of supported and unsupported information. Some parts accurately reflect the document, but other significant parts are either not found in the document (unsupported) or contradict the information present in the document (contradictory).
2 - Mostly Unfaithful:** The majority of the response is not supported by the document or directly contradicts the information provided. There might be minimal overlap, but the core message misrepresents or significantly deviates from the source document.
1 - Not Faithful:** The response is completely unsupported by the document, presents information that directly contradicts the document, hallucinates information, or is entirely unrelated to the document's content.

**Example Scenario:**

**Document:**
Singapore, officially the Republic of Singapore, is a sovereign island city-state in maritime Southeast Asia. It lies about one degree of latitude (137 kilometres or 85 miles) north of the equator, off the southern tip of the Malay Peninsula... Modern Singapore was founded in 1819 by Sir Stamford Raffles as a British trading post. Singapore is known for its strong international trade links and multicultural population.

**Question (for context):**
Tell me about Singapore's founding.

**Response:**
Singapore was founded in 1819 by Sir Stamford Raffles. It gained independence at that time and quickly became a major agricultural exporter in Southeast Asia.

**Justification:**
The response correctly states that modern Singapore was founded in 1819 by Sir Stamford Raffles, which is supported by the document. However, it incorrectly claims Singapore gained independence in 1819 (the document doesn't mention independence) and falsely states it became a major agricultural exporter (the document mentions trade links but not specifically agriculture). These unsupported and contradictory statements make the response mostly unfaithful.

**Rating:** 2
---

**Now, it's your turn to evaluate a new response based on the provided document using the same scale:**

**Document:**
{DOCUMENT}

**Question (for context):**
{QUESTION}

**Response:**
{RESPONSE}

"""


JUDGE_ANSWER_QUALITY_PROMPT="""You are tasked with evaluating the quality and correctness of a response in relation to a given question. Your goal is to determine how well the response answers the question, focusing on accuracy, completeness, and relevance.

Please read the document (for context), the question, and the response carefully. Then, rate the response based on its quality in answering the question using the following criteria:

**Answer Quality Rating Scale:**

5 - Excellent Answer:** The response is factually accurate, fully addresses all parts of the question completely, and is directly relevant. It provides a clear and comprehensive solution to the user's query.
4 - Good Answer:** The response is factually accurate and addresses the main parts of the question well. It might miss a minor detail or nuance, or could be slightly clearer, but overall provides a correct and useful answer.
3 - Partial Answer:** The response addresses some parts of the question correctly but contains significant omissions or inaccuracies regarding other parts. Or, it might provide generally correct information that only tangentially answers the specific question asked. It offers some value but is incomplete or partially flawed.
2 - Poor Answer:** The response contains significant factual inaccuracies, fails to address the core of the question, or is largely irrelevant. It provides little value in answering the user's query.
1 - Inadequate Answer:** The response is completely factually incorrect, makes no attempt to answer the question, or is entirely off-topic/irrelevant.

**Example Scenario:**

**Document:**
Singapore, officially the Republic of Singapore, is a sovereign island city-state in maritime Southeast Asia. It lies about one degree of latitude (137 kilometres or 85 miles) north of the equator... Modern Singapore was founded in 1819 by Sir Stamford Raffles as a British trading post.

**Question:**
Tell me about Singapore's founding and its current major industries.

**Response:**
Singapore was founded by Sir Stamford Raffles in 1819. Its primary industry is currently agriculture and fishing.

**Justification:**
The founding information is correct. However, the claim about major industries (agriculture and fishing) is factually incorrect for modern Singapore. While the response attempts to answer both parts, a significant part of the answer is wrong.

**Rating:** 3
---

**Now, it's your turn to evaluate a new response based on the provided document (for context) and question using the scale above:**

**Document:**
{DOCUMENT}

**Question:**
{QUESTION}

**Response:**
{RESPONSE}

"""